runtime: python3.8
env: standard

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
