apiVersion: v1
kind: Pod
metadata:
  name: astergam-app
spec:
  template:
    spec:
      containers:
      - name: astergam-app-container
        image: gcr.io/uptimerobotmonitors/demo:v1.0.0
        volumeMounts:
        - name: astergam-volume
          mountPath: /data
      volumes:
      - name: astergam-volume
        emptyDir: {}