apiVersion: v1
kind: Pod
metadata:
  name: astergam-app-pod
spec:
  containers:
  - name: astergam-app-container
    image: gcr.io/uptimerobotmonitors/demo:v1.0.0
    env:
    - name: TheName
      valueFrom:
        secretKeyRef:
          name: astergam-secret
          key: username
    - name: ThePassword
      valueFrom:
        secretKeyRef:
          name: astergam-secret
          key: password
  restartPolicy: Never