apiVersion: v1
kind: Deployment
metadata:
  name: astergam-app
spec:
  template:
    spec:
      containers:
      - name: astergam-app-container
        image: gcr.io/uptimerobotmonitors/demo:v1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"