apiVersion: v1
kind: Pod
metadata:
  name: astergam-app
spec:
  template:
    spec:
      containers:
      - name: astergam-app-container
        image: gcr.io/uptimerobotmonitors/demo:v1.0.0
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8000
          name: http