---
apiVersion: v1
kind: Pod
metadata:
  name: astergam-app
spec:
  replicas: 4
  selector:
    matchLabels:
    app: astergam-app
  template:
    metadata:
      labels:
        app: astergam-app
    spec:
      containers:
      - name: astergam-app-container
        image: gcr.io/uptimerobotmonitors/demo:v1.0.0
        ports:
        - cointainerPort: 8080
          name: http